// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl:
    | 'https://edge.affectively.ai/v1'
    | 'https://edge.affectively.ai'
    | 'https://affectively-edge-dev.taylorbuley.workers.dev'
    | (string & {});
};

export type ChatCompletionRequest = {
  /**
   * Model identifier. Can be:
   * - Text models: "mistral-7b", "llama-70b", "llama-13b", "glm-4.7", "qwen-edit", "tinyllama-1.1b", "deepseek-1.5b", "deepseek-3b"
   * - Vision: "flux-4b"
   * - Audio: "vibevoice-9b"
   * - Translation: "translategemma-4b"
   * - Special modes: "ensemble" (multiple models), "auto" (best available)
   *
   */
  model: string;
  /**
   * Array of message objects forming the conversation history.
   * Each message has a role (system, user, assistant) and content.
   *
   */
  messages: Array<Message>;
  /**
   * Controls randomness. Lower = more deterministic, Higher = more creative
   * - 0: Deterministic (best for analysis)
   * - 0.7: Balanced (recommended for most tasks)
   * - 1.5+: Creative (for brainstorming)
   *
   */
  temperature?: number;
  /**
   * Maximum number of tokens to generate
   */
  max_tokens?: number;
  /**
   * Nucleus sampling. Controls diversity of top choices.
   * Only used when temperature > 0
   *
   */
  top_p?: number;
  /**
   * Only sample from the K most likely tokens.
   * For reducing output variability without lowering temperature.
   *
   */
  top_k?: number;
  /**
   * For ensemble mode: array of model IDs to use.
   * Each model receives the same input and outputs are combined.
   *
   */
  models?: Array<string>;
  /**
   * How to combine ensemble results:
   * - weighted_average: Combine based on confidence scores
   * - voting: Majority rule
   * - consensus: Only return if models agree above threshold
   * - synthesis: AI-generated synthesis of perspectives
   *
   */
  ensemble_strategy?: 'weighted_average' | 'voting' | 'consensus' | 'synthesis';
  /**
   * Optional metadata for advanced modalities
   */
  metadata?: {
    /**
     * Enable multi-layer reasoning analysis
     */
    enable_meta_metacognition?: boolean;
    /**
     * Depth of self-reflection (1-5 layers)
     */
    reflection_depth?: number;
    /**
     * Enable probabilistic Monte Carlo analysis
     */
    enable_monte_carlo?: boolean;
    /**
     * Number of Monte Carlo iterations
     */
    iterations?: number;
    /**
     * Type of Monte Carlo analysis
     */
    analysis_type?:
      | 'probability_estimation'
      | 'risk_analysis'
      | 'scenario_analysis';
    /**
     * Optional cache key for repeated requests
     */
    cache_key?: string;
  };
};

export type Message = {
  /**
   * Role of the message sender
   */
  role: 'system' | 'user' | 'assistant';
  content:
    | string
    | Array<
        | {
            type?: string;
            text?: string;
          }
        | {
            type?: string;
            image_url?: {
              url?: string;
              detail?: 'low' | 'high';
            };
          }
      >;
};

export type ChatCompletionResponse = {
  /**
   * Unique completion ID
   */
  id?: string;
  object?:
    | 'chat.completion'
    | 'chat.completion.ensemble'
    | 'chat.completion.monte_carlo';
  /**
   * Unix timestamp of creation
   */
  created?: number;
  /**
   * Model used for completion
   */
  model?: string;
  usage?: Usage;
  choices?: Array<Choice>;
};

export type Choice = {
  finish_reason?: 'stop' | 'length' | 'error';
  index?: number;
  message?: Message;
  /**
   * Results when using ensemble mode
   */
  ensemble_results?: {
    consensus_confidence?: number;
    perspectives?: Array<{
      [key: string]: unknown;
    }>;
  };
  /**
   * Results when using Monte Carlo analysis
   */
  monte_carlo_results?: {
    point_estimate?: number;
    confidence_interval?: {
      [key: string]: unknown;
    };
    standard_deviation?: number;
    iterations_converged?: number;
  };
};

export type Usage = {
  /**
   * Number of tokens in the prompt
   */
  prompt_tokens?: number;
  /**
   * Number of tokens in the completion
   */
  completion_tokens?: number;
  /**
   * Total tokens used (prompt + completion)
   */
  total_tokens?: number;
};

export type EmbeddingsRequest = {
  /**
   * Text or array of texts to embed
   */
  input: string | Array<string>;
  /**
   * Model to use for embeddings
   */
  model: string;
};

export type EmbeddingsResponse = {
  object?: string;
  data?: Array<{
    object?: string;
    embedding?: Array<number>;
    index?: number;
  }>;
  model?: string;
  usage?: Usage;
};

export type ModelsResponse = {
  object?: string;
  data?: Array<{
    id?: string;
    object?: string;
    created?: number;
    owned_by?: string;
    permissions?: Array<{
      [key: string]: unknown;
    }>;
    root?: string;
    parent?: string;
    context_window?: {
      input_tokens?: number;
      output_tokens?: number;
    };
    capabilities?: Array<
      'chat' | 'embeddings' | 'vision' | 'function_calling' | 'reasoning'
    >;
    rate_limit?: {
      requests_per_minute?: number;
      tokens_per_minute?: number;
    };
  }>;
};

export type HealthResponse = {
  status?: 'operational' | 'degraded' | 'offline';
  timestamp?: string;
  gateway?: {
    status?: string;
    latency_ms?: number;
  };
  providers?: {
    [key: string]: {
      status?: string;
      latency_ms?: number;
      available_models?: number;
    };
  };
  rate_limits?: {
    current_usage?: number;
    limit?: number;
    reset_at?: string;
  };
  cache?: {
    hit_rate?: number;
    items_cached?: number;
  };
};

export type ErrorResponse = {
  error?: {
    message?: string;
    type?: string;
    param?: string;
    code?: string;
  };
};

export type RateLimitError = {
  error?: {
    type?: string;
    message?: string;
  };
  rate_limit?: {
    limit_per_minute?: number;
    remaining?: number;
    reset_in_seconds?: number;
  };
};

export type CreateChatCompletionData = {
  body: ChatCompletionRequest;
  headers?: {
    /**
     * Optional request ID for tracking
     */
    'X-Request-ID'?: string;
    /**
     * Optional correlation ID for distributed tracing
     */
    'X-Correlation-ID'?: string;
  };
  path?: never;
  query?: never;
  url: '/chat/completions';
};

export type CreateChatCompletionErrors = {
  /**
   * Invalid request parameters
   */
  400: ErrorResponse;
  /**
   * Rate limit exceeded
   */
  429: RateLimitError;
  /**
   * Server error
   */
  500: ErrorResponse;
};

export type CreateChatCompletionError =
  CreateChatCompletionErrors[keyof CreateChatCompletionErrors];

export type CreateChatCompletionResponses = {
  /**
   * Successful completion
   */
  200: ChatCompletionResponse;
};

export type CreateChatCompletionResponse =
  CreateChatCompletionResponses[keyof CreateChatCompletionResponses];

export type CreateEmbeddingsData = {
  body: EmbeddingsRequest;
  path?: never;
  query?: never;
  url: '/embeddings';
};

export type CreateEmbeddingsErrors = {
  /**
   * Invalid request
   */
  400: ErrorResponse;
};

export type CreateEmbeddingsError =
  CreateEmbeddingsErrors[keyof CreateEmbeddingsErrors];

export type CreateEmbeddingsResponses = {
  /**
   * Successful embeddings generation
   */
  200: EmbeddingsResponse;
};

export type CreateEmbeddingsResponse =
  CreateEmbeddingsResponses[keyof CreateEmbeddingsResponses];

export type ListModelsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/models';
};

export type ListModelsResponses = {
  /**
   * List of available models
   */
  200: ModelsResponse;
};

export type ListModelsResponse = ListModelsResponses[keyof ListModelsResponses];

export type GetHealthData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/health';
};

export type GetHealthErrors = {
  /**
   * Gateway is unavailable
   */
  503: HealthResponse;
};

export type GetHealthError = GetHealthErrors[keyof GetHealthErrors];

export type GetHealthResponses = {
  /**
   * Gateway is operational
   */
  200: HealthResponse;
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];
