import { definePackageBuildConfig } from '@a0n/a0/package-build';

export default definePackageBuildConfig({
  tsconfig: 'tsconfig.build.json',
  entry: {
    index: 'src/index.ts',
    'data/storage/index': 'src/data/storage/index.ts',
    'data/sync/index': 'src/data/sync/index.ts',
    'compute/index': 'src/compute/index.ts',
    'compute/gateway/index': 'src/compute/gateway/index.ts',
    'compute/distributed/index': 'src/compute/distributed/index.ts',
    'compute/inference/index': 'src/compute/inference/index.ts',
    'compute/rlhf/index': 'src/compute/rlhf/index.ts',
    'compute/buleyean/index': 'src/compute/buleyean/index.ts',
    'react/index': 'src/react/index.ts',
    'auth/index': 'src/auth/index.ts',
    'deploy/index': 'src/deploy/index.ts',
    'agent/index': 'src/agent/index.ts',
    'agent/core/index': 'src/agent/core/index.ts',
    'agent/guardrails/index': 'src/agent/guardrails/index.ts',
    'agent/memory/index': 'src/agent/memory/index.ts',
    'agent/orchestration/index': 'src/agent/orchestration/index.ts',
    'agent/tracing/index': 'src/agent/tracing/index.ts',
    'agent/eval/index': 'src/agent/eval/index.ts',
    'agent/edge/index': 'src/agent/edge/index.ts',
    'agent/transport/index': 'src/agent/transport/index.ts',
    'agent/wasm/index': 'src/agent/wasm/index.ts',
    'agent/react/index': 'src/agent/react/index.ts',
    'agent/mcp/index': 'src/agent/mcp/index.ts',
  },
  format: ['cjs', 'esm'],
  dts: false,
  sourcemap: true,
  clean: false,
  treeshake: true,
  minify: false,
  external: ['@anthropic-ai/sdk', 'react'],
});
